### ISSUE TITLE
Please support new UI of leetcode

### ISSUE THREAD

**Issue by LLiiaung** [HaolinZhong/PMCA#1]
We recognize the importance of continuous evolution and improvement in the tech world, and it's no different when it comes to platforms like LeetCode. The new user interface (UI) of LeetCode promises a more streamlined, user-friendly, and intuitive experience for its community. Supporting the new UI means embracing the future of coding challenges and providing users with a modern platform that's both efficient and engaging. We urge everyone to give the new UI a chance and provide constructive feedback to make it even better. Together, we can ensure that LeetCode remains the go-to platform for coding enthusiasts worldwide.

**Comment by HaolinZhong** [comment]
Thanks for the advice. The commit ee3d906 has solved the issue and now PMCA supports all UI of both Leetcode and Leetcode-CN.

**Comment by LLiiaung** [comment]
That's great, thank you!
