### ISSUE TITLE
The extension is not working for me

### ISSUE THREAD

**Issue by An9el0baby** [HaolinZhong/PMCA#12]
After clicking the submit button, the extension has no response. 
I tried with different Chrome users.

**Comment by HaolinZhong** [comment]
Hi,
I have also observed this problem, thanks for letting me know. A possible reason might be that Leetcode made some modification on its frontend elements. A quick fix for now would be using the split view instead of the dynamic layout in Leetcode. I will try to solve this bug in the next version.

**Comment by An9el0baby** [comment]
Thank You!

**Comment by An9el0baby** [comment]
It seems like the split view is also down now.

**Comment by HaolinZhong** [comment]
The newest version 0.9.4 has fixed this issue.
