### ISSUE TITLE
Cannot Update Review Due

### ISSUE THREAD

**Issue by three-three-three** [HaolinZhong/PMCA#13]
Hi,

Thank you so much for your job! Today I installed PMCA on my chrome. When I resubmitted the problem in "Review Due", the record just won't disappear, still a red DELAY. Can you tell me what should I do?

**Comment by sunrise-cn** [comment]
Hi,
I hava the same problem on Edge.

**Comment by HaolinZhong** [comment]
Hi, I have also observed this problem. It might be due to that LeetCode updated some critical frontend widget, causing PMCA failed to function. I will fix this problem within this weekend.

**Comment by sunrise-cn** [comment]
Thank you.

**Comment by HaolinZhong** [comment]
The newest version 0.9.4 has fixed this issue.
