### ISSUE TITLE
该更新了

### ISSUE THREAD

**Issue by 7878k** [HaolinZhong/PMCA#14]
加点新功能

**Comment by HaolinZhong** [comment]
请说明具体需要的功能

**Comment by 7878k** [comment]
ctrl + enter 可以更新下，这个蛮方便的。
然后加一个自动更新代码到git的， 有个插件 leethub专门做这个的

**Comment by HaolinZhong** [comment]
- 在添加新的feature, 比如`ctrl` + `enter`之前, 我会重构一次PMCA的代码, 这会比较花时间, 而且最近是final season, 所以年前不会添加新的feature了
- 自动同步代码到git的feature的优先级比较低, 因为已经有leetHub了, 短期内不会做
