### ISSUE TITLE
the request new feature button overlapping with next page button

### ISSUE THREAD

**Issue by yl-to** [HaolinZhong/PMCA#17]
<img width="500" alt="Screenshot 2023-12-25 at 8 59 48 PM" src="https://github.com/HaolinZhong/PMCA/assets/23205976/f2d62ddc-caf6-4c72-bdb2-812ea9fa5566">

**Comment by HaolinZhong** [comment]
Could you please let me know the resolution of your screen?

for now you can enter the number in the input box and press `enter` to switch between pages

**Comment by HaolinZhong** [comment]
close this issue as the extension UI has a larger height now
