### ISSUE TITLE
Sort Problems by Delay (and/or Progess/Level/Problem Number)

### ISSUE THREAD

**Issue by TianshuPang** [HaolinZhong/PMCA#18]

**Comment by HaolinZhong** [comment]
Thank you for raising this issue. Yes, it's a good feature. I will include it in the second next release.

**Comment by TianshuPang** [comment]
> Thank you for raising this issue. Yes, it's a good feature. I will include it in the second next release.

Appreciate it! BTW do you have an ETA (No hurry, take your time)?

**Comment by HaolinZhong** [comment]
around mid April, if everything goes fine in the next webpack release

**Comment by TianshuPang** [comment]
@HaolinZhong A friendly check in 🐶 Any updated ETA?

**Comment by HaolinZhong** [comment]
我在人生的道路上迷失了(just joking...) I forgot about this thing as I'm really busy these days. Will finish this in this weekend.
