### ISSUE TITLE
有时点击扩展程序图标要等好久(2s以上)才能弹出菜单，影响体验

### ISSUE THREAD

**Issue by Lyshc-cgc** [HaolinZhong/PMCA#23]
如题😢，不知道具体原因。有时要等好久才弹出菜单（扩展程序图标显示的特性是被点击后的特效，背后有阴影），有时又很快，点一下就出来了。Chrome 127.0.6533.120, win11

**Comment by HaolinZhong** [comment]
我想应该是因为extension的UI用了太多从别的地方加载的东西(字体, icon之类的)了... 如果在国内那就可能会比较慢. 这个我短期内会优化一下. 

题目同步功能也会涉及到网络请求, 也可能是慢的原因, 不过这个就不那么好在短期内解决了. 可以只在需要同步的时候开启同步功能, 完成同步后马上关掉.

谢谢反馈👍

**Comment by Lyshc-cgc** [comment]
> 我想应该是因为extension的UI用了太多从别的地方加载的东西(字体, icon之类的)了... 如果在国内那就可能会比较慢. 这个我短期内会优化一下.
> 
> 题目同步功能也会涉及到网络请求, 也可能是慢的原因, 不过这个就不那么好在短期内解决了. 可以只在需要同步的时候开启同步功能, 完成同步后马上关掉.
> 
> 谢谢反馈👍

期待更新
