### ISSUE TITLE
The extension doesn't work

### ISSUE THREAD

**Issue by xingyu-long** [HaolinZhong/PMCA#26]
Tried it with both Brave and Chrome browser on https://leetcode.com/ and didn't see any records from extension

**Comment by HaolinZhong** [comment]
Please use the "inspect" function provided chrome to check the chrome console. If PMCA is correctly installed, when you browse a leetcode page in the console you should be able to see `Hello PMCA!`.  Upon a successful submission, there should be many logs being printed in the console. 

<img width="353" alt="image" src="https://github.com/user-attachments/assets/d0b86f2b-fbbd-4239-8b52-c267afe6ff32">

**Comment by xingyu-long** [comment]
@HaolinZhong Thanks for help! it seems working after submitted a few times.
