### ISSUE TITLE
Is it possible to set up a pop-up reminder when it's time for review

### ISSUE THREAD

**Issue by Zfttter** [HaolinZhong/PMCA#28]
Is it possible to set up a pop-up reminder when it's time for review

**Comment by HaolinZhong** [comment]
这个可以做, 但是感觉不是很有必要. 
对于做题比较多的用户可能会一直弹窗, 会比较烦人. 
再一个就是做弹窗需要额外向chrome要权限, 发布时审核起来会比较麻烦.
