### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Zfttter** [HaolinZhong/PMCA#29]
我先是做了一个题A 接着在5分钟之后复习了题A，接着做题B，但是做完题B之后发现复习进度直接变成了20%=两天后复习，而不是一开始的10%=5分钟后复习。以及后面所有再做的题都是在第一次做完时就归类到了20%

**Comment by HaolinZhong** [comment]
你好, 你看到的应该不是一个bug. 
PMCA对不同难度的题目设置了不同的复习时间. 对于hard的题目, 会按照1, 2, 4, 7, 15天这个时间间隔来安排复习. 对于medium的题目, 间隔就弱化为2, 7, 15. easy的题目的间隔进一步弱化为2, 7.

**Comment by Zfttter** [comment]
> 你好, 你看到的应该不是一个bug. PMCA对不同难度的题目设置了不同的复习时间. 对于hard的题目, 会按照1, 2, 4, 7, 15天这个时间间隔来安排复习. 对于medium的题目, 间隔就弱化为2, 7, 15. easy的题目的间隔进一步弱化为2, 7.

谢谢您！原来是这样！非常科学！要是可以自定义间隔时间就更好了哈哈哈哈哈 期待更新！
