### ISSUE TITLE
Sometimes clicking commit doesn't make review go away

### ISSUE THREAD

**Issue by yiruoyanyu** [HaolinZhong/PMCA#5]
maybe because network？sometimes it makes

**Comment by yiruoyanyu** [comment]
100019. 将数组分割成最多数目的子数组 | 20% | Medium | 24 hours
-- | -- | -- | --
100076. 无限数组的最短子数组 | 20% | Medium | 23 hours
2522. 将字符串分割成值不超过 K 的子字符串

[100019. 将数组分割成最多数目的子数组](https://leetcode.cn/problems/split-array-into-maximum-number-of-subarrays/)	
20%
Medium

24 hours
[100076. 无限数组的最短子数组](https://leetcode.cn/problems/minimum-size-subarray-in-infinite-array/)	
20%
Medium

23 hours
[2522. 将字符串分割成值不超过 K 的子字符串](https://leetcode.cn/problems/partition-string-into-substrings-with-values-at-most-k/)

这几个问题，不能被提交清楚，是否是因为题目号的原因，其余的题目都可以

**Comment by HaolinZhong** [comment]
谢谢你的反馈!

从题号判断, 这几道题应当是比较新的题目 (100019, 100076), 在我点进去之后它们的题目已经显示为2871, 2875等. 
我推测这个问题的根源是力扣修改了前端的题号:

- 在你第一次提交时, 题号为100019, 100076, PMCA会以这些题号作为key来存储题目的记录
- 力扣官方修改了问题的题号
- 在你后续复习时, 题号已经改变为2xxx, 这时PMCA根据这个key不能找到原本的题目, 所以不会更新复习进度 (但可能把这道题作为一道新题加入了Review Scheduled的部分)

后续为了解决这个问题, 我可能会添加一个功能: 删除题目的记录. 这样在遇到这种奇怪的情况的时候你可以直接把这些数据删掉.

**Comment by yiruoyanyu** [comment]
谢谢你的回复，你这个插件很有用，感谢你的开源工作



---Original---
From: ***@***.***&gt;
Date: Thu, Oct 5, 2023 00:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [HaolinZhong/PMCA] Sometimes clicking commit doesn't make reviewgo away (Issue #5)




 
谢谢你的反馈!
 
从题号判断, 这几道题应当是比较新的题目 (100019, 100076), 在我点进去之后它们的题目已经显示为2871, 2875等.
 我推测这个问题的根源是力扣修改了前端的题号:
  
在你第一次提交时, 题号为100019, 100076, PMCA会以这些题号作为key来存储题目的记录
 
力扣官方修改了问题的题号
 
在你后续复习时, 题号已经改变为2xxx, 这时PMCA根据这个key不能找到原本的题目, 所以不会更新复习进度 (但可能把这道题作为一道新题加入了Review Scheduled的部分)
  
后续为了解决这个问题, 我可能会添加一个功能: 删除题目的记录. 这样在遇到这种奇怪的情况的时候你可以直接把这些数据删掉.

**Comment by HaolinZhong** [comment]
commit a2f49d9 solved this issue
