### ISSUE TITLE
Pagination blocked by request new feature and donation buttons

### ISSUE THREAD

**Issue by frankzengjj** [HaolinZhong/PMCA#7]
<img width="494" alt="Screenshot 2023-10-05 at 12 09 13 AM" src="https://github.com/HaolinZhong/PMCA/assets/20346113/0968ebb1-3c85-4204-bd31-e9b71052edb7">

as shown in the screenshot, i am not able to click next button or enter page number. This happened in the Review Scheduled tab but I am not sure if To Review would have the same issue

**Comment by HaolinZhong** [comment]
Well, I guess I underestimated the possible height of this page... It will be fixed in the next release

**Comment by HaolinZhong** [comment]
commit a2f49d9 solved this issue
